### ISSUE TITLE
Error: Unable to find plugin "gatsby-remark-classes". 

### ISSUE THREAD

**Issue by Etheonor** [chrisg86/gatsby-remark-classes#1]
Hello!

I discovered this plugin and I was really happy, until I tried to launch it ^^ 

The plugin is in my node_modules folder, I followed the tutorial and used this command line : 
npm install --save gatsby-remark-classes

But still, when I launch my site with "gatsby develop", the log says that the package was not installed.

I don't know what's wrong...

**Comment by chrisg86** [comment]
Thanks for reporting this, I'll take a look!

**Comment by chrisg86** [comment]
I have published version `0.1.2`. Please try it out by updating to that version.

**Comment by Etheonor** [comment]
It fixed the issue, thank you very much!
