### ISSUE TITLE
Blockquote doesn't seem to work

### ISSUE THREAD

**Issue by kamalarieff** [chrisg86/gatsby-remark-classes#4]
Hi there, I'm trying to add some tailwind classes to the `blockquote` tag but it doesn't seem to be working. Here's my code snippet: 

```js
{
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-classes`,
            options: {
              classMap: {
                blockquote: "border border-l-4 border-gray-400",
              }
            }
          }
        ]
      }
    }
```

I've already referred to the `classMap` [documentation ](https://github.com/syntax-tree/mdast#nodes)and I think I'm doing it right.

Am I setting the configurations right?

**Comment by chrisg86** [comment]
Thanks for reporting this. I'll have a look as soon as I can.

**Comment by chrisg86** [comment]
Which version of `gatsby-remark-classes` are you using? I tried your configuration and it worked for me. 

Could you inspect the element in questions with chrome dev tools and verify that the class attribute is not set accordingly?

**Comment by chrisg86** [comment]
<img width="753" alt="Blockquote" src="https://user-images.githubusercontent.com/4715597/69915502-7871da80-142e-11ea-8c31-cb570b1579ef.png">
